language: node_js
node_js:
  - 7
  - 6
  - 4
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'react-webpack-template' ]; then cd .. && eval "mv $currentfolder react-webpack-template" && cd react-webpack-template; fi
